config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  scope :find_newest_article, -> { order(created_at: :desc).limit(5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/jobs/application_job.rb
class ApplicationJob < ActiveJob::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @q = Post.order(created_at: :desc).ransack(params[:q])
    @posts = @q.result.page(params[:page]).per(2)
    @new_posts = Post.find_newest_article
    @author = Author.first
  end

  def show
    
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to @post
  end

  def edit
    
  end

  # なぜ.editメソッドではないのか??

  def update
    @post.update(post_params)
    redirect_to @post
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

 private
  def post_params
    params.require(:post).permit(:title, :body, :category)
  end

  def set_post
    @post = Post.find(params[:id])
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
      <div class="container">
       
       <%= link_to "My blog", posts_path, class: "navbar-brand" %>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="ナビゲーションの切替">
            <%# <%= link_to "My blog", root_path, class:"navbar-brand" %> 
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
             
              <%= link_to "投稿する", new_post_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class = "row">
  <div class="col-md-12">
    <h1>ブログ記事の編集</h1>
    <%= form_with model: @post, local: true do |form| %>
      <div class="form-group">
      <%= form.label "タイトル" %>
      <%= form.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
      <%= form.label "カテゴリ" %>
      <%= form.text_field :categorry,class: "form-control" %>
      </div>
      <div class="form-group">
      <%= form.label "本文" %>
      <%= form.text_area :body,class: "form-control" %>
      </div>
      <%= form.submit "編集する", class: "btn btn-primary" %>
    <% end %>
  </div>  
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="form-inline float-right mb-3">
      <%= search_form_for @q do |f| %>
        <div class = "form-group">
          <%= f.search_field :title_or_body_cont,placeeholder:"タイトルか本文を検索", class:"form-control" %>
          <%= f.submit "検索", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <% @posts.each do |post| %>
      <div class="article">
        <h2 class = "post_title">タイトル:<%= post.title %></h2>
        <p>カテゴリ:<%= post.category %></p>
        <p>作成日:<%= post.created_at %></p>
        <p><%= truncate(post.body, length: 50) %></p>
      <p><%= link_to "続きを読む", post, class: "btn btn-info" %></p>
      </div>
    <% end %>  
    <%= paginate @posts %>
   
  </div>


 <div class="col-md-4">
   <div class="card">
       <%= image_tag @author.image_url, class: "card-img-top", alt: "著者イメージ" %>
       <div class="card-body"> 
         <h3>著者名：<%= @author.name %></h3>
         <p>詳細：<%= @author.description %></p>
       </div>
       <div class="list-group">
        <% @new_posts.each do |post| %>
          <%# <% break if index >= 5 %> 
          <%= link_to post.title, post, class: "list-group-item post_title" %>
        <% end %>
       </div>
  </div>
 </div>


</div>

app/views/posts/new.html.erb
<div class = "row">
  <div class="col-md-12">
    <h1>ブログ記事投稿</h1>
    <%= form_with model: @post, local: true do |form| %>
      <div class="form-group">
      <%= form.label "タイトル" %>
      <%= form.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
      <%= form.label "カテゴリ" %>
      <%= form.text_field :categorry,class: "form-control" %>
      </div>
      <div class="form-group">
      <%= form.label "本文" %>
      <%= form.text_area :body,class: "form-control" %>
      </div>
      <%= form.submit "登録する", class: "btn btn-primary" %>
    <% end %>
  </div>  
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-12">
  <h1><%= @post.title %></h1>
  <p>カテゴリ: <%= @post.category %></p>
  <p>投稿日: <%= @post.created_at %></p>
  <hr>
  <%= simple_format(@post.body) %>
  <hr>
  <%= link_to "編集", edit_post_path(@post), class: "btn btn-secoundry"  %>
  <%= link_to "削除", post_path(@post), class: "btn btn-danger",method: :delete  %>
  <%# <%= link_to "削除", post_path(@post), class: "btn btn-danger", method: :delete %>
  </div>
</div>